export default [
    {
        id: 1,
        name: "Shadow",
        img: "assets/squirrels/1.webp",
        color: "Black",
        favoriteFood: "Sunflower seeds",
        typicalActivity: "Twilight foraging",
        tailLengthInches: 7,
        friendlyToHumans: true,
        commonHabitat: "Deciduous forests",
    },
    {
        id: 2,
        name: "Amber",
        img: "assets/squirrels/2.webp",
        color: "Brown",
        favoriteFood: "Acorns",
        typicalActivity: "Daytime scavenging",
        tailLengthInches: 8,
        friendlyToHumans: false,
        commonHabitat: "Urban parks",
    },
    {
        id: 3,
        name: "Rusty",
        img: "assets/squirrels/3.webp",
        color: "Red",
        favoriteFood: "Pine nuts",
        typicalActivity: "Early morning foraging",
        tailLengthInches: 6.5,
        friendlyToHumans: false,
        commonHabitat: "Coniferous forests",
    },
    {
        id: 4,
        name: "Chip",
        img: "assets/squirrels/4.webp",
        color: "Chipmunk",
        favoriteFood: "Berries",
        typicalActivity: "Afternoon gathering",
        tailLengthInches: 5,
        friendlyToHumans: true,
        commonHabitat: "Mixed woodlands",
    }
]
