export default [
    {
        id: 1,
        name: "Mallard",
        img: "mallard.jpg",
        latinName: "Anas platyrhynchos",
        eggsLayed: "9",
        maleWeightLbs: 2.7,
        femaleWeightLbs: 2.4,
        location: "North America",
        foundInCanada: true,
    },
    {
        id: 2,
        name: "Cinnamon Teal",
        img: "cinnamon-teal.jpg",
        latinName: "Spatula cyanoptera",
        eggsLayed: "8-10",
        maleWeightLbs: 0.7,
        femaleWeightLbs: 0.8,
        location: "Western United States",
        foundInCanada: true,
    },
    {
        id: 3,
        name: "Australasian Shoveler",
        img: "australasian-shoveler.jpg",
        latinName: "Spatula rhynchotis",
        eggsLayed: "10",
        maleWeightLbs: 1.8,
        femaleWeightLbs: 1.6,
        location: "Australia & New Zealand",
        foundInCanada: false,
    },
    {
        id: 4,
        name: "Mandarin Duck",
        img: "mandarin-duck.jpg",
        latinName: "Aix galericulata",
        eggsLayed: "9-12",
        maleWeightLbs: 1.4,
        femaleWeightLbs: 2.4,
        location: "Asia",
        foundInCanada: false,
    },
    {
        id: 5,
        name: "Steller's Eider",
        img: "stellers-eider.jpg",
        latinName: "Polysticta stelleri",
        eggsLayed: "5-6",
        maleWeightLbs: 1.9,
        femaleWeightLbs: 1.9,
        location: "Russia & Alaska",
        foundInCanada: true,
    },
    {
        id: 6,
        name: "Redhead",
        img: "redhead-duck.jpg",
        latinName: "Aythya americana",
        eggsLayed: "7-10",
        maleWeightLbs: 2.4,
        femaleWeightLbs: 2.1,
        location: "North Central North America",
        foundInCanada: true,
    },
    {
        id: 7,
        name: "Wood Duck",
        img: "wood-duck.jpg",
        latinName: "Aix sponsa",
        eggsLayed: "12",
        maleWeightLbs: 1.5,
        femaleWeightLbs: 1.4,
        location: "North America",
        foundInCanada: true,
    },
    {
        id: 8,
        name: "Blue Duck",
        img: "blue-duck.jpg",
        latinName: "Hymenolaimus malacorhynchos",
        eggsLayed: "4-9",
        maleWeightLbs: 2.6,
        femaleWeightLbs: 1.9,
        location: "New Zealand",
        foundInCanada: false,
    },
    {
        id: 9,
        name: "Northern Shoveler",
        img: "northern-shoveler.jpg",
        latinName: "Spatula clypeata",
        eggsLayed: "9",
        maleWeightLbs: 1.5,
        femaleWeightLbs: 1.4,
        location: "Central North America",
        foundInCanada: true,
    }
]